name: ShipLock
main: me.lolikillyaaa.ShipLock.Main
version: 1.0
author: Lolikillyaaa
description: >
             Ship Lock Plugin.
commands:
  lockship:
    description: Locks ship!
  lockedships:
    description: Views locked ship locations.
  lockshipclear:
    description: Clears all locks!
  ls:
    description: Locks ship!
  vls:
    description: Views locked ship locations.
  lc:
    description: Clears all locks!
